-- AlterTable
ALTER TABLE "User" ADD COLUMN "Bio" TEXT;
ALTER TABLE "User" ADD COLUMN "City" TEXT;
ALTER TABLE "User" ADD COLUMN "Country" TEXT;
ALTER TABLE "User" ADD COLUMN "PhoneNumber" INTEGER DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "PostalCode" TEXT;
