
version: 2.1


orbs:
  
  node: circleci/node@4.7
jobs:
  build:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo

    steps: 
      - checkout       

        
      - run: echo "this is in the pipeline"
            
workflows:
    build:
      jobs: 
        - build 
          #context: sonarCloud
