version: 2.1

orbs:
  node: circleci/node@4.7
jobs:
  build:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
              cd src 
              npm install
              npm install mocha --save-dev

      - run:
          name: Run tests
          command: npm run test

workflows:
  build:
    jobs:
      - build
